name: Native Build

on: [push, pull_request]

jobs:
  build:

    runs-on: [windows-2022]

    strategy:
      matrix:
        toolset: [v142, v143]
        configuration: [RelWithDebInfo]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Configure
      run: cmake -B build/${{matrix.toolset}} -G "Visual Studio 17 2022" -A x64 -T ${{matrix.toolset}}
    - name: Build
      run: cmake --build build/${{matrix.toolset}} --config ${{matrix.configuration}}
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: OcctImportJS_Win_${{matrix.toolset}}_${{matrix.configuration}}.lib
        path: build/${{matrix.toolset}}/${{matrix.configuration}}/occt-import-js.lib
