name: Native Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{matrix.os-type}}

    strategy:
      matrix:
        os-type: [windows-2022, macos-12]
        configuration: [RelWithDebInfo]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Configure
      run: cmake -B ${{github.workspace}}/build
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.configuration}}
