name: WASM Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{matrix.os-type}}

    strategy:
      matrix:
        os-type: [windows-2022]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup node.js 17.x
      uses: actions/setup-node@v2
      with:
        node-version: 17.x
    - name: Get Emscripten
      run: ./tools/setup_emscripten_win.bat
    - name: Build WASM
      run: ./tools/build_wasm_win.bat Release
    - name: Update Package
      run: npm install
    - name: Run Test
      run: npm run test
